package com.example.bankblood.Utils;

/**
 * Created by E610 on 3/30/2018.
 */

public class Constants {

    public final static String apiBasicUrl="https://donor.frb.io/api/";
    public  final static String basicUrl="https://donor.frb.io";
    public final static String accessToken="Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImI4N2ZmMmJhN2FkYTQ4MTFjZmNjZjQ5ZDZiOGQ3MDk0NDdlZGUzMTkzYTJhYTBiN2VlZTFiMzMwNzYwMjVjNTA4Y2Y0YjkyMmI5ZjJiYjU3In0.eyJhdWQiOiIyIiwianRpIjoiYjg3ZmYyYmE3YWRhNDgxMWNmY2NmNDlkNmI4ZDcwOTQ0N2VkZTMxOTNhMmFhMGI3ZWVlMWIzMzA3NjAyNWM1MDhjZjRiOTIyYjlmMmJiNTciLCJpYXQiOjE1MjMwMTUyMTUsIm5iZiI6MTUyMzAxNTIxNSwiZXhwIjoxNTU0NTUxMjE1LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.DpahytXeO9pWK8toH7Ch4rej8az_hgkWaNMZIzEtXnt3mteqiUCfHmB11WNczRZEM1-uturJKgqBqCNZQOHN-I8fexHSedIGJtYqY74l0HJujL4pSGYxN_9yTxh2aOMCLdGdyKwiqgCn6rqSXpOG-ARUzGDbwM5hjM_IhPC5HqLKv84u91cbvihIjqCKlQxjAsZFyCNLCnwF_PrJhanzPhczphwVlMq8_putyWA9ZqB_dWZlaNJzV8prRfDbVE1apx4SuERmt4SpTtwUmvFooCwagEQHXQEbBJoib1yQRhHo5LA4mcLYxAmnSGZBYdQuR3-zWgu8RWMszG84Wlb7LZyfGKDUvABRhq7Ps4wTplAyJmex1gqWLd0yUmKbjBIz6DUeAxV3EJAd6VNQCZpkDJGwLXYlYXiN1CaoqxoZKH-JjG-9KR4-hylzvNSdLWHXKAV8Smf5jVIGtlidmKLIIkSdnhDJJgl4FgFYfDyPS5rcZS1FPpm2z5oLdopzazhYEMk_SPluZP0MFNoGcXcTHbcDxtOLCnbcIZ48CGwmHZZIYDC_t8S0AqTux_xjkWAKZOusLdtYVSEnfzfCckgYY7FwsFx4qBXvmMCMEu4Yx9gDHf94Gccrb27lMB1EYga447psuigkoC6a96-lwInyzDduwVOzCs03GoPHBT3Wcu0";

}
